Aufgabe 3b
FabianTsch/gantry pull request #11
Opened 2023-01-25 09:10 UTC by FabianTsch

- [ ] update _gyro_frame_scalar
- [ ] update _accell_frame_scalar

2023-01-30 20:29 UTC, FabianTsch commented
Ich habe noch Debug versuch gestartet ohne erfolg. Ich habe you den Komponeten Debugger, den der Prof hochgeladen hat, hinzugefügt. Hat aber auch nicht viel gebracht. Ich würde den Pull-Request freigeben und mergen und das Lösen dieses Problems auf später verschieben, wenn wir einen Komilitonen fragen können zum vergleichen. 


@NSB4130

2023-01-31 10:20 UTC, NSB4130 requested changes

2023-01-31 10:20 UTC, NSB4130 commented on gantry.py
> +        dp_vector=np.array([[dp1],[dp2],[dphi]])
hier ausberssern: 
dp_vector=np.array([[dp1],[dp2],[dpphi]])

2023-01-31 10:30 UTC, NSB4130 approved these changes

2023-01-31 10:31 UTC, merged